version: '3.3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:${ELK_VERSION}
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    stdin_open: true
    tty: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '50'
    networks:
      - elk
  kibana:
    container_name: kibana
    image: kibana:${ELK_VERSION}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '50'
    networks:
      - elk
  logstash:
    container_name: logstash
    image: logstash:${ELK_VERSION}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./configs/logstash.template.json:/usr/share/logstash/templates/logstash.template.json
    ports:
      - 5044:5044
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '50'
    networks:
      - elk
networks:
  elk:
    driver: bridge
